backend:
  name: git-gateway
  branch: main

local_backend: false

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "models"
    label: "Models"
    label_singular: "Model"
    folder: "content/models"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "name", label: "Model Name", widget: "string" }
      - { name: "title", label: "Set Title / Subtitle", widget: "string" }
      - { name: "cover", label: "Cover Image", widget: "image" }
      - { name: "images", label: "Gallery Images", widget: "list", field: { name: "image", label: "Image", widget: "image" } }
      - { name: "published", label: "Published", widget: "boolean", default: true }
      - { name: "date", label: "Date", widget: "datetime", format: "YYYY-MM-DD" }
